packages:
  - ./fs-routing
  - ./react-router
  - ./react-router-cloudfront-spa/app
  - ./react-router-cloudfront-spa/cdk
  - ./react-router-cloudfront-spa/cdk/function

overrides:
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  globals: ^17
  minimatch@<3.1.3: '>=3.1.3'
  minimatch@<3.1.4: '>=3.1.4'
  '@eslint/eslintrc>minimatch': '3.1.4'
  eslint>minimatch: '3.1.4'
