packages:
  - ./fs-routing
  - ./react-router
  - ./react-router-cloudfront-spa/app
  - ./react-router-cloudfront-spa/cdk
  - ./react-router-cloudfront-spa/cdk/function

overrides:
  '@eslint/eslintrc>ajv': ^6.12.4
  ajv@<8.18.0: '>=8.18.0'
  eslint>ajv: ^6.12.4
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
