packages:
  - ./fs-routing
  - ./react-router
  - ./react-router-cloudfront-spa/app
  - ./react-router-cloudfront-spa/cdk
  - ./react-router-cloudfront-spa/cdk/function

overrides:
  glob@>=10.3.7 <=11.0.3: '>=11.1.0'
