packages:
  - ./basic
  - ./fs-routing
  - ./react-router

overrides:
  ajv@>=7.0.0-alpha.0 <8.18.0: '>=8.18.0'
  esbuild@<=0.24.2: '>=0.27.0'
  minimatch@<3.1.4: '>=3.1.4'
  '@eslint/eslintrc>minimatch': '3.1.4'
  eslint>minimatch: '3.1.4'
