name: Build and Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
    - main

  workflow_dispatch: null
jobs:
  ci:
    strategy:
      matrix:
        path:
          - preact
          - react

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
      with:
        persist-credentials: false

    - name: Install pnpm ${{ matrix.path }}
      uses: pnpm/setup@v2.1.0
      with:
        working-directory: ${{ matrix.path }}
        install: false

    - name: Install global dependencies ${{ matrix.path }}
      run: pnpm -g add esbuild

    - name: Install dependencies ${{ matrix.path }}
      working-directory: ./${{ matrix.path }}
      run: pnpm install --no-frozen-lockfile

    - name: lint ${{ matrix.path }}
      working-directory: ./${{ matrix.path }}
      run: pnpm lint

    - name: build ${{ matrix.path }}
      working-directory: ./${{ matrix.path }}
      run: pnpm build
